# Generated by Django 4.2.2 on 2023-06-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proyect')),
            ],
        ),
    ]
